apiVersion: v1
kind: List
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: ServiceEntry
  metadata:
    name: google
  spec:
    hosts:
    - "*.google.com"
    ports:
    - number: 443
      name: https
      protocol: HTTPS