apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-service-b
  labels:
    app: sample-web-service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-web-service-b
  template:
    metadata:
      labels:
        app: sample-web-service-b
    spec:
      containers:
      - name: service
        image: sample-web-service-b:0.0.2
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          exec:
            command: ["curl", "-f", "http://localhost:8080/actuator/health"]
        readinessProbe:
          exec:
            command: ["curl", "-f", "http://localhost:8080/actuator/health"]
